require("gneves.plugins-setup")
require("gneves.core.options")
require("gneves.core.keymaps")
require("gneves.core.colorscheme")
require("gneves.plugins.comment")
require("gneves.plugins.nvim-tree")
require("gneves.plugins.lualine")
require("gneves.plugins.telescope")
require("gneves.plugins.nvim-cmp")
require("gneves.plugins.lsp-config")
-- require("gneves.plugins.copilot")
